-- Crear Tabla de Recetas (con nombre como PK)
CREATE TABLE IF NOT EXISTS recetas (
    nombre VARCHAR(255) PRIMARY KEY,
    calorias INT NOT NULL,
    carbohidratos INT NOT NULL,
    proteinas INT NOT NULL,  
    grasas INT NOT NULL,
    fibra INT NOT NULL, 
    azucares INT NOT NULL,
    pasos TEXT NOT NULL,
    consejos TEXT,
    rutaImagen VARCHAR(255) 
) ENGINE=InnoDB;

-- Crear tabla de Ingredientes
CREATE TABLE IF NOT EXISTS ingredientes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

-- Crear tabla de Recetas_Ingredientes (relación muchos a muchos)
CREATE TABLE IF NOT EXISTS recetas_ingredientes (
    fk_nombre_receta VARCHAR(255) NOT NULL,
    fk_id_ingrediente INT NOT NULL,
    cantidad DOUBLE  NULL,
    unidadMedida VARCHAR(50)  NULL,
    PRIMARY KEY (fk_nombre_receta, fk_id_ingrediente),
    FOREIGN KEY (fk_nombre_receta) REFERENCES recetas(nombre) ON DELETE CASCADE,
    FOREIGN KEY (fk_id_ingrediente) REFERENCES ingredientes(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ingredientes de prueba
INSERT INTO ingredientes (nombre) VALUES
('Aceite de coco'),
('Aceite de oliva virgen extra'),
('Aceite de sésamo'),
('Aceite de trufa'),
('Aceitunas negras'),
('Aceitunas verdes'),
('Aguacate'),
('Agua'),
('Ajo'),
('Ajo en polvo'),
('Ajo negro'),
('Albahaca fresca'),
('Alcaparras'),
('Almendra cruda'),
('Almendra molida'),
('Almendras laminadas'),
('Anchoas en lata'),
('Atún en agua'),
('Avena sin gluten molida'),
('Azafrán en hebras'),
('Bacalao desalado'),
('Berenjena'),
('Bonito fresco'),
('Boniato'),
('Brócoli'),
('Caballa en aceite de oliva virgen extra'),
('Caballa fresca'),
('Calabacín'),
('Calabaza'),
('Caldo de carne sin azúcar'),
('Caldo de pescado sin azúcar'),
('Caldo de pollo sin azúcar'),
('Caldo de verduras sin azúcar'),
('Camarones pelados'),
('Canela'),
('Cebolla blanca'),
('Cebolla morada'),
('Cebolleta'),
('Cebollino'),
('Chalota'),
('Champiñones'),
('Cilantro fresco'),
('Coco aminos'),
('Codornices limpias'),
('Col lombarda'),
('Col rizada'),
('Coles de Bruselas'),
('Coliflor'),
('Comino'),
('Conejo troceado'),
('Contramuslo de pollo sin piel'),
('Copos de chile'),
('Corazones de alcachofa'),
('Corvina en filete'),
('Crema de cacahuete 100%'),
('Crema de leche sin azúcar'),
('Cúrcuma'),
('Curry en polvo'),
('Dorada limpia'),
('Eneldo fresco'),
('Escamas de parmesano'),
('Espárragos trigueros'),
('Espárragos verdes'),
('Espinacas frescas'),
('Estrella de anís'),
('Filete de lubina'),
('Filete de merluza'),
('Filete de rape'),
('Filete de ternera magra'),
('Frutos rojos frescos'),
('Gambas peladas'),
('Gambones pelados'),
('Garbanzos cocidos'),
('Granada'),
('Guindilla fresca roja'),
('Guindilla seca'),
('Habas blancas en conserva'),
('Habas frescas'),
('Habas rojas en conserva'),
('Harina de almendra'),
('Harina de coco'),
('Hierbabuena fresca'),
('Hierbas provenzales'),
('Hinojo'),
('Hoja de laurel'),
('Hoja de lima kaffir'),
('Hojas grandes de lechuga iceberg'),
('Lechuga iceberg'),
('Hojas grandes de lechuga romana'),
('Huevos'),
('Jamón serrano'),
('Jengibre fresco'),
('Jengibre en polvo'),
('Judías verdes'),
('Lechuga romana'),
('Leche de coco ligera sin azúcar'),
('Leche evaporada'),
('Lenguado en filete'),
('Lentejas beluga cocidas'),
('Lentejas rojas'),
('Lentejas cocidas'),
('Lima'),
('Limón'),
('Lomo de bacalao desalado'),
('Lomo de cerdo en filetes'),
('Lomo de cerdo en medallones'),
('Maíz cocido en conserva'),
('Mango en cubos'),
('Mantequilla'),
('Manzana verde'),
('Mayonesa sin azúcar'),
('Mejillones frescos'),
('Menta fresca'),
('Mero en filete'),
('Mezcla de hojas verdes'),
('Mostaza de Dijon sin azúcar'),
('Mozzarella rallada'),
('Nata líquida para cocinar sin azúcar'),
('Nuez moscada'),
('Nueces'),
('Orégano'),
('Pan rallado'),
('Pan sin gluten'),
('Pasta de curry rojo'),
('Pasta de curry verde'),
('Pasta de miso sin gluten'),
('Patatas baby'),
('Pavo cocido en lonchas o dados'),
('Pavo picado'),
('Pechuga de pavo'),
('Pechuga de pollo'),
('Pechuga de pollo cocida y desmenuzada'),
('Pechuga de pato'),
('Pepino'),
('Perejil fresco'),
('Pez espada en filete'),
('Pimienta negra'),
('Pimentón dulce'),
('Pimentón ahumado'),
('Pimiento asado en tiras'),
('Pimiento rojo'),
('Pimiento verde'),
('Pimiento amarillo'),
('Piñones'),
('Puerro'),
('Pulpo cocido'),
('Queso cottage'),
('Queso curado'),
('Queso de cabra sin lactosa'),
('Queso emmental'),
('Queso feta sin lactosa'),
('Queso fresco batido'),
('Queso havarti'),
('Queso mozzarella'),
('Queso parmesano'),
('Queso rallado sin lactosa'),
('Queso ricotta sin lactosa'),
('Quinoa cocida'),
('Rábanos'),
('Rape en medallones'),
('Romero fresco'),
('Rúcula'),
('Sal común'),
('Sal gruesa'),
('Salmón ahumado'),
('Salmón fresco'),
('Salmón marinado casero'),
('Salsa de pescado'),
('Salsa de tomate natural sin azúcar'),
('Salsa tamari sin gluten'),
('Semillas de calabaza'),
('Semillas de chía'),
('Semillas de lino molidas'),
('Semillas de sésamo'),
('Semillas de sésamo tostadas'),
('Sepia limpia'),
('Setas variadas'),
('Solomillo de cerdo en medallones'),
('Tahini'),
('Tallo de hierba limón'),
('Tempeh en dados'),
('Ternera picada'),
('Ternera en tiras finas'),
('Tofu firme'),
('Tomate cherry'),
('Tomate natural'),
('Tomate seco sin azúcar'),
('Tomate triturado natural sin azúcar'),
('Tomillo fresco'),
('Trucha en lomos'),
('Vieiras limpias'),
('Vinagre de manzana'),
('Vino blanco'),
('Yogur griego natural sin azúcar'),
('Zanahoria'),
('Champiñones Portobello'),
('Col repollo'),
('Crema agria'),
('Filete de pavo'),
('Frutos secos picados'),
('Hojas de col repollo'),
('Miel'),
('Queso pecorino rallado'),
('Ternera en láminas finas'),
('Tortilla sin gluten'),
('Alga wakame'),
('Pesto casero sin azúcar'),
('Brotes de soja'),('Chile rojo'),
('Langostinos cocidos'),
('Bacalao fresco'),
('Pollo picado'),
('Langostinos pelados'),
('Apio'),('Naranja'),
('Calamares limpios'),
('Pollo'),
('Pollo en tiras'),
('Pavo en dados'),
('Cebolla chalota'),
('Ternera'),
('Cordero picado'),
('Pimiento rojo asado en tiras'),
('Pollo cocido y desmenuzado'),
('Shiitake'),
('Magret de pato'),
('Anís estrellado'),
('Patata baby'),
('Mini pepperoni'),
('Tomates cherry enteros pelados'),
('Sazonador de fajitas'),
('Guacamole'),
('Entrecot');

-- Recetas de prueba opcionales
-- Nota: El orden de los valores numéricos es: Calorías, Carbohidratos, Proteínas, Grasas, Fibra, Azúcares.


 